# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genai.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'genai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgenai.proto\x12\x05genai\"#\n\x0fQuestionRequest\x12\x10\n\x08question\x18\x01 \x01(\t\" \n\x0e\x41nswerResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2L\n\x0cGenAiService\x12<\n\x0b\x41skQuestion\x12\x16.genai.QuestionRequest\x1a\x15.genai.AnswerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUESTIONREQUEST']._serialized_start=22
  _globals['_QUESTIONREQUEST']._serialized_end=57
  _globals['_ANSWERRESPONSE']._serialized_start=59
  _globals['_ANSWERRESPONSE']._serialized_end=91
  _globals['_GENAISERVICE']._serialized_start=93
  _globals['_GENAISERVICE']._serialized_end=169
# @@protoc_insertion_point(module_scope)
